import { useQuery } from "@tanstack/react-query";

const FAKE_PEOPLE = Array.from({ length: 100 }, (_, i) => {
  const firstNames = [
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Nancy",
    "Daniel",
    "Lisa",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Kimberly",
    "Paul",
    "Emily",
    "Andrew",
    "Donna",
    "Joshua",
    "Michelle",
    "Kenneth",
    "Dorothy",
    "Kevin",
    "Carol",
    "Brian",
    "Amanda",
    "George",
    "Melissa",
    "Edward",
    "Deborah",
    "Ronald",
    "Stephanie",
    "Timothy",
    "Rebecca",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Kathleen",
    "Gary",
    "Amy",
    "Nicholas",
    "Shirley",
    "Eric",
    "Angela",
    "Jonathan",
    "Helen",
    "Stephen",
    "Anna",
    "Larry",
    "Brenda",
    "Justin",
    "Pamela",
    "Scott",
    "Nicole",
    "Brandon",
    "Emma",
    "Benjamin",
    "Samantha",
    "Samuel",
    "Katherine",
    "Raymond",
    "Christine",
    "Gregory",
    "Debra",
    "Frank",
    "Rachel",
    "Alexander",
    "Catherine",
    "Patrick",
    "Carolyn",
    "Jack",
    "Janet",
    "Dennis",
    "Ruth",
    "Jerry",
    "Maria",
  ];

  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
  ];

  const jobTitles = [
    "Software Engineer",
    "Product Manager",
    "UX Designer",
    "Data Scientist",
    "Marketing Manager",
    "Sales Director",
    "HR Manager",
    "Financial Analyst",
    "DevOps Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "QA Engineer",
    "Project Manager",
    "Scrum Master",
    "Business Analyst",
    "Content Writer",
    "Graphic Designer",
    "SEO Specialist",
    "Customer Success Manager",
    "Account Executive",
    "Operations Manager",
    "CEO",
    "CTO",
    "CFO",
    "VP of Engineering",
    "VP of Sales",
    "VP of Marketing",
    "Senior Developer",
    "Junior Developer",
    "Intern",
    "Consultant",
    "Architect",
  ];

  const firstName = firstNames[i % firstNames.length];
  const lastName = lastNames[Math.floor(i / 2) % lastNames.length];
  const fullName = `${firstName} ${lastName}`;
  const jobTitle = jobTitles[i % jobTitles.length];

  return {
    id: (i + 1).toString(),
    name: fullName.toLowerCase().replace(" ", "_"),
    displayName: fullName,
    jobTitle: jobTitle,
    avatar: `https://i.pravatar.cc/150?img=${(i % 70) + 1}`, // pravatar has 70 images
  };
});

const FAKE_TOPICS = [
  "javascript",
  "typescript",
  "react",
  "nodejs",
  "python",
  "java",
  "csharp",
  "golang",
  "rust",
  "swift",
  "kotlin",
  "flutter",
  "reactnative",
  "vue",
  "angular",
  "svelte",
  "nextjs",
  "remix",
  "astro",
  "webdev",
  "frontend",
  "backend",
  "fullstack",
  "devops",
  "cloud",
  "aws",
  "azure",
  "gcp",
  "docker",
  "kubernetes",
  "terraform",
  "cicd",
  "testing",
  "tdd",
  "agile",
  "scrum",
  "design",
  "ux",
  "ui",
  "figma",
  "tailwind",
  "css",
  "html",
  "accessibility",
  "performance",
  "security",
  "database",
  "sql",
  "nosql",
  "mongodb",
  "postgresql",
  "redis",
  "graphql",
  "rest",
  "api",
  "microservices",
  "serverless",
  "mobile",
  "ios",
  "android",
  "gaming",
  "ai",
  "machinelearning",
  "blockchain",
  "web3",
  "crypto",
  "startup",
  "productivity",
  "career",
  "learning",
  "opensource",
  "github",
  "coding",
  "programming",
  "tech",
  "software",
  "engineering",
  "developer",
  "code",
  "build",
  "deploy",
  "debug",
  "refactor",
  "architecture",
  "patterns",
  "bestpractices",
  "tips",
  "tutorial",
  "howto",
  "guide",
  "news",
  "update",
  "release",
  "announcement",
  "community",
].map((topic, i) => ({
  id: (i + 1).toString(),
  name: topic,
}));

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export const usePeopleSearch = (query: string) => {
  return useQuery({
    queryKey: ["people", "search", query],
    queryFn: async () => {
      await delay(1000);

      const filtered = FAKE_PEOPLE.filter((person) =>
        query === "" || query === "skip"
          ? true
          : person.displayName.toLowerCase().includes(query.toLowerCase())
      ).slice(0, query === "" || query === "skip" ? 10 : 5);

      return filtered.map((person) => ({
        id: person.id,
        display: `@${person.displayName}`,
        data: {
          name: person.displayName,
          username: person.name,
          jobTitle: person.jobTitle,
          image: person.avatar,
        },
      }));
    },
    staleTime: 1000 * 60 * 5,
    enabled: query !== "skip",
  });
};

export const useTopicSearch = (query: string) => {
  return useQuery({
    queryKey: ["topics", "search", query],
    queryFn: async () => {
      await delay(1000);

      const filtered = FAKE_TOPICS.filter((topic) =>
        query === "" || query === "skip"
          ? true
          : topic.name.includes(query.toLowerCase())
      ).slice(0, query === "" || query === "skip" ? 10 : 5);

      return filtered.map((topic) => ({
        id: topic.id,
        display: `#${topic.name}`,
        data: {
          name: topic.name,
        },
      }));
    },
    staleTime: 1000 * 60 * 5,
    enabled: query !== "skip",
  });
};
